## ----eval=FALSE----------------------------------------------------------
## R CMD build --help

## ----eval=FALSE----------------------------------------------------------
## R CMD INSTALL --help

## ----eval=FALSE----------------------------------------------------------
## R CMD check --help

## ----eval=FALSE----------------------------------------------------------
## package.skeleton() # "in "fresh" session ("anRpackage")
## package.skeleton("pkgname") # in "fresh" session
## 
## set.seed(02138)
## f <- function(x, y) x+y
## g <- function(x, y) x-y
## d <- data.frame(a = 1, b = 2)
## e <- rnorm(1000)
## package.skeleton(list = c("f","g","d","e"), name = "pkgname")

## ----eval=FALSE----------------------------------------------------------
## devtools::create("path/to/package/pkgname")

## ----eval=FALSE----------------------------------------------------------
## git init
## git add *
## git commit -m "First commit"
## git remote add origin git@github.com:harvard-P01/pkgtemplate.git
## git push -u origin master

## ----eval=FALSE----------------------------------------------------------
## devtools::install_github("harvard-P01/pkgtemplate")

## ----eval=FALSE----------------------------------------------------------
## devtools::install_github("harvard-P01/pkgtemplate",
##                          build_vignettes = TRUE)

## ----eval=FALSE----------------------------------------------------------
## .Rproj.user
## .Rhistory
## .RData

## ----eval=FALSE----------------------------------------------------------
## # History files
## .Rhistory
## .Rapp.history
## 
## # Example code in package build process
## *-Ex.R
## 
## # RStudio files
## .Rproj.user/
## 
## # produced vignettes
## vignettes/*.html
## vignettes/*.pdf

## ----eval=FALSE----------------------------------------------------------
## Version: 1.0
## 
## RestoreWorkspace: Default
## SaveWorkspace: Default
## AlwaysSaveHistory: Default
## 
## EnableCodeIndexing: Yes
## UseSpacesForTab: Yes
## NumSpacesForTab: 2
## Encoding: UTF-8
## 
## RnwWeave: knitr
## LaTeX: pdfLaTeX
## 
## AutoAppendNewline: Yes
## StripTrailingWhitespace: Yes
## 
## BuildType: Package
## PackageUseDevtools: Yes
## PackageInstallArgs: --no-multiarch --with-keep.source

## ----eval=TRUE-----------------------------------------------------------
linmodEst <- function(x, y) {
  ## compute QR-decomposition of x
  qx <- qr(x)
  ## compute (x’x)^(-1) x’y
  coef <- solve.qr(qx, y)
  ## degrees of freedom and standard deviation of residuals
  df <- nrow(x) - ncol(x)
  sigma2 <- sum((y - x %*% coef) ^ 2) / df
  ## compute sigma^2 * (x’x)^-1
  vcov <- sigma2 * chol2inv(qx$qr)
  colnames(vcov) <- rownames(vcov) <- colnames(x)
  list(
    coefficients = coef,
    vcov = vcov,
    sigma = sqrt(sigma2),
    df = df
  )
}

## ------------------------------------------------------------------------
data(cats, package = "MASS")
linmodEst(cbind(1, cats$Bwt), cats$Hwt)

## ------------------------------------------------------------------------
lm1 <- lm(Hwt ~ Bwt, data=cats)
lm1
coef(lm1)

## ------------------------------------------------------------------------
vcov(lm1)
summary(lm1)$sigma

## ----eval=FALSE----------------------------------------------------------
## #' Linear regression
## #'
## #' Runs an OLS regression not unlike \code{\link{lm}}
## #'
## #' @param y response vector (1 x n)
## #' @param X covariate matrix (p x n) with no intercept
## #'
## #' @return A list with 4 elements: coefficients, vcov, sigma, df
## #'
## #' @examples
## #' data(mtcars)
## #' X <- as.matrix(mtcars[, c("cyl", "disp", "hp")])
## #' y <- mtcars[, "mpg"]
## #' linreg(y, X)
## #'
## #' @export
## #'
## linmodEst <- function(x, y) {
##   ## compute QR-decomposition of x
##   qx <- qr(x)
##   ## compute (x’x)^(-1) x’y
##   coef <- solve.qr(qx, y)
##   ## degrees of freedom and standard deviation of residuals
##   df <- nrow(x) - ncol(x)
##   sigma2 <- sum((y - x %*% coef) ^ 2) / df
##   ## compute sigma^2 * (x’x)^-1
##   vcov <- sigma2 * chol2inv(qx$qr)
##   colnames(vcov) <- rownames(vcov) <- colnames(x)
##   list(
##     coefficients = coef,
##     vcov = vcov,
##     sigma = sqrt(sigma2),
##     df = df
##   )
## }

## ----eval=FALSE----------------------------------------------------------
## % Generated by roxygen2 (4.1.1): do not edit by hand
## % Please edit documentation in R/linmodEst.R
## \name{linmodEst}
## \alias{linmodEst}
## \title{Linear regression}
## \usage{
## linmodEst(x, y)
## }
## \arguments{
## \item{y}{response vector (1 x n)}
## 
## \item{X}{covariate matrix (p x n) with no intercept}
## }
## \value{
## A list with 4 elements: coefficients, vcov, sigma, df
## }
## \description{
## Runs an OLS regression not unlike \code{\link{lm}}
## }
## \examples{
## data(mtcars)
## X <- as.matrix(mtcars[, c("cyl", "disp", "hp")])
## y <- mtcars[, "mpg"]
## linmodEst(y, X)
## }

## ----eval=FALSE----------------------------------------------------------
## Package: pkgtemplate
## Type: Package
## Title: What the Package Does (Title Case)
## Version: 0.1
## Date: 2015-10-24
## Author: Who wrote it
## Maintainer: Who to complain to <yourfault@somewhere.net>
## Description: More about what it does (maybe more than one line)
## License: What license is it under?
## LazyData: TRUE

## ----eval=FALSE----------------------------------------------------------
## export(linmodEst)

## ------------------------------------------------------------------------
hello <- function() {
 s <- "Hello World!"
 class(s) <- "hi"
 return(s)
}

hello()

## ------------------------------------------------------------------------
print.hi <- function(...) {
  print("Surprise!")
}

hello()

## ------------------------------------------------------------------------
linmod <- function(x, ...)
  UseMethod("linmod")

## ------------------------------------------------------------------------
linmod.default <- function(x, y, ...) {
  x <- as.matrix(x)
  y <- as.numeric(y)
  est <- linmodEst(x, y)
  est$fitted.values <- as.vector(x %*% est$coefficients)
  est$residuals <- y - est$fitted.values
  est$call <- match.call()
  class(est) <- "linmod"
  return(est)
}

## ------------------------------------------------------------------------
print.linmod <- function(x, ...) {
  cat("Call:\n")
  print(x$call)
  cat("\nCoefficients:\n")
  print(x$coefficients)
}

## ------------------------------------------------------------------------
x <- cbind(Const = 1, Bwt = cats$Bwt)
y <- cats$Hw
mod1 <- linmod(x, y)
mod1

## ----eval=FALSE----------------------------------------------------------
## linmod.formula <- function(formula, data = list(), ...) {
##   mf <- model.frame(formula = formula, data = data)
##   x <- model.matrix(attr(mf, "terms"), data = mf)
##   y <- model.response(mf)
##   est <- linmod.default(x, y, ...)
##   est$call <- match.call()
##   est$formula <- formula
##   return(est)
## }

## ----eval=FALSE----------------------------------------------------------
## devtools::use_testthat()

## ----eval=FALSE----------------------------------------------------------
## data(cats, package = "MASS")
## l1 <- linmod(Hwt ~ Bwt * Sex, data = cats)
## l2 <- lm(Hwt ~ Bwt * Sex, data = cats)
## 
## test_that("same estimated coefficients as lm function", {
##   expect_equal(l1$coefficients, l2$coefficients)
## })

## ----eval=FALSE----------------------------------------------------------
## ==> devtools::test()
## 
## Loading pkgtemplate
## Loading required package: testthat
## Testing pkgtemplate
## .
## Woot!

## ----eval=FALSE----------------------------------------------------------
## devtools::use_vignette("linmod")

## ------------------------------------------------------------------------
fibo <- function(n) {
  if (n == 0)
    return(0)
  if (n == 1)
    return(1)
  return(fibo(n - 1) + fibo(n - 2))
}

## ----eval=FALSE----------------------------------------------------------
## system.time(fibo(35))

## ------------------------------------------------------------------------
library(Rcpp)
fibRcpp <- cppFunction( '
int fibo(const int n) {
   if (n == 0)
      return(0);
   if (n == 1)
      return(1);
   return (fibo(n - 1)) + fibo(n - 2);
}
' )

## ------------------------------------------------------------------------
fibRcpp

## ------------------------------------------------------------------------
system.time(print(fibRcpp(35)))

## ----eval=FALSE----------------------------------------------------------
## devtools::use_rcpp()

## ----eval=FALSE----------------------------------------------------------
## Rcpp::Rcpp.package.skeleton("pkg")
## RcppArmadillo::RcppArmadillo.package.skeleton("pkg")

## ----eval=FALSE----------------------------------------------------------
## #include <RcppArmadillo.h>
## using namespace Rcpp;
## 
## // [[Rcpp::export]]
## List fastLm(const arma::vec & y, const arma::mat & X) {
## 
##   int n = X.n_rows, k = X.n_cols;
## 
##   arma::colvec coef = arma::solve(X, y);
##   arma::colvec resid = y - X*coef;
## 
##   double sig2 = arma::as_scalar(arma::trans(resid)*resid/(n-k));
##   arma::colvec stderrest =
##     arma::sqrt(sig2 * arma::diagvec( arma::inv(arma::trans(X)*X)) );
## 
##   return List::create(Named("coefficients") = coef,
##                       Named("stderr")       = stderrest);
## }

## ------------------------------------------------------------------------
library(pkgtemplate)
data(mtcars)
x <- as.matrix(cbind(1, mtcars[, 2:4]))
y <- as.vector(mtcars[, 1])

## ------------------------------------------------------------------------
pkgtemplate::fastLm(y, x)

## ------------------------------------------------------------------------
summary(lm(y ~ x - 1))

